apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp
  template:
    metadata:
      labels:
        app: chatapp
    spec:
      containers:
        - name: chatapp
          image: codechoreographer/m324-chatapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
      restartPolicy: Always

