name: CI/CD Pipeline

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  lint-build-test:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Linter
        run: npx eslint . --ext .ts

      - name: Build Project
        run: npm run build

      - name: Run Tests
        run: npm test

  deploy:
    needs: lint-build-test
    runs-on: self-hosted
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t codechoreographer/m324-chatapp:latest .

      - name: Push Docker image
        run: docker push codechoreographer/m324-chatapp:latest

      - name: Deploy to Kubernetes (simuliert)
        run: echo "Deployment auf Kubernetes funktioniert"
